### ISSUE TITLE
How to change colour of cloud

### ISSUE THREAD

**Issue by dmresearch15** [shikokuchuo/ichimoku#7]
Is there any way to change the colour of cloud (say green for upward trend or red for downward trend)?

**Comment by shikokuchuo** [comment]
This is technically not an issue to implement. However varying the colour of the cloud is strictly a later addition that is not part of the original ichimoku system. If you are able to provide a link to an article or extract from a book etc. that refers to the colour of the cloud (as a useful element of the system rather than just a convention), I would consider this.

The Senkou A and Senkou B lines are already different colours, which allows you to distinguish in any case. I think I may enable custom themes as an option so you can make the difference more obvious if needed.

**Comment by shikokuchuo** [comment]
Custom themes have been enabled in 3bc668e which is CRAN release 1.3.1.

**Comment by dmresearch15** [comment]
I've re-installed the package from CRAN release 1.3.1. But the themes remains as before.

**Comment by shikokuchuo** [comment]
The built-in themes are the same. What is new is the ability to specify a custom theme yourself (as a vector of 12 colour values that map to different elements of the chart). As an example:

```
library(ichimoku)
cloud <- ichimoku(sample_ohlc_data)
custom_theme <- c("#ffffcc", "#ff0000", "#00ff00", "#737373", "#1f1f1f", "#b8b8b8", "#1a1a1a", "#1a1a1a", "#1a1a1a", "#ffffff", "#333333", "#1a1a1a")
plot(cloud, theme = custom_theme)
```

**Comment by shikokuchuo** [comment]
I am closing this for now due to inactivity. If there is justification for re-opening please do so. Thanks for raising.
